typography_spectrum: 0.2095185441430658
color:
  brandStrength: 0.7108646281994879
  lightness: 0.8851803261786699
  saturation: 0.9479110937099904
  rhythmicContrast: 0.9976186943240464
  brandColors:
    - '#232323'
    - '#787878'
    - '#979797'
    - '#4E4E4E'
    - '#CFCFCF'
layout_spectrum: 0.33993582567200065
author:
  name: Keric
  email: keric@keric.com
  url: 'http://www.keric.com'
name: Yoga Fett
navigation:
  - name: Home
    id: ae02d005-a6b2-4e0e-8466-654498f28c5f
    type: content
  - name: About
    id: a9fa804d-34ad-4e9f-af83-9dce6619b822
    type: content
  - name: Schedule
    id: 02511bad-7427-43a4-b129-32fc4dc8a137
    type: content
  - name: Instagram
    url: 'https://www.instagram.com/kericyoga/'
    type: external
  - name: Contact
    id: 5d246332-3eeb-4d14-b5cf-6d535a2e3731
    type: content
title: Yoga Fett
description: Least feared pose hunter in the galaxy
