typography_spectrum: 0.2095185441430658
color:
  brandStrength: 0.7108646281994879
  lightness: 0.8851803261786699
  saturation: 0.9479110937099904
  rhythmicContrast: 0.9976186943240464
  brandColors:
    - '#232323'
    - '#787878'
    - '#979797'
    - '#4E4E4E'
    - '#CFCFCF'
layout_spectrum: 0.33993582567200065
author:
  name: Keric
  email: keric@keric.com
  url: 'http://www.keric.com'
name: Yoga Fett
title: Least feared pose hunter in the galaxy
description: Least feared pose hunter in the galaxy
